#Loading and Pre-processing Data

In [ ]:
#importing libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
from sklearn.datasets import fetch_20newsgroups

import glob
import os

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
# For unzipping dataset from google drive
# !unrar x "/content/drive/MyDrive/20newsbydate.rar" "/content/drive/My Drive"

In [ ]:
# Importing data from drive

import os
os.chdir('/content/drive/MyDrive/20newsbydate/20news-bydate-train')

all_subdirs = [d for d in os.listdir('.') if os.path.isdir(d)]

print(all_subdirs)


['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


In [ ]:
# choosing a subset of classes

all_subdirs = all_subdirs[ :4]
print(all_subdirs)
all_subdirs = all_subdirs[ :4]
corpus = []
y = []
c=0

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware']


In [ ]:
# Loading data from files

path = "/content/drive/MyDrive/20newsbydate/20news-bydate-train/"

for i in all_subdirs:
  
 
  x=path + i + "/*"
  
  files = glob.glob(x)
  # print(files)
 
  for i in range(len(files)):
    
   with open(files[i], encoding="utf8", errors='ignore') as f:

      
      
      data = f.read().replace('\n', '')
      
      review = re.sub('[^a-zA-Z]', ' ', data)
      review = review.lower()
      review = review.split()
      ps = PorterStemmer()
      all_stopwords = stopwords.words('english')
      all_stopwords.remove('not')
      review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
      review = ' '.join(review)
      
      corpus.append(review)

In [ ]:
# Loading data from files

path = "/content/drive/MyDrive/20newsbydate/20news-bydate-train/"
c=0
for j  in all_subdirs:
  
  x=path + j + "/*"
  
  files = glob.glob(x)
  for j in range(len(files)):
    y.append(c)
  c+=1

In [ ]:
# Not part of code .... !!!!
print(len(corpus))
print(len(corpus[0]))
print(len(y))
X_train =[]

for i in corpus:
   X_train.append(i.split(" "))

print(X_train[0])
print(len(X_train))

2245
1859
2245
['mango', 'cs', 'umd', 'edu', 'charley', 'wingat', 'subject', 'gospel', 'datinglin', 'benedikt', 'rosenau', 'write', 'argument', 'goe', 'follow', 'q', 'oid', 'quot', 'appear', 'john', 'not', 'almost', 'codifi', 'way', 'matthew', 'luke', 'howev', 'consid', 'similar', 'enough', 'point', 'knowledg', 'q', 'not', 'entir', 'differ', 'sourc', 'assum', 'present', 'accur', 'see', 'argumentr', 'lead', 'firm', 'conclus', 'materi', 'john', 'not', 'sureexactli', 'refer', 'take', 'grant', 'similarityto', 'matt', 'luke', 'q', 'materi', 'differ', 'henc', 'one', 'could', 'almostani', 'relationship', 'two', 'right', 'john', 'get', 'straight', 'fromjesu', 'mouth', 'talk', 'date', 'text', 'not', 'age', 'author', 'usual', 'explan', 'time', 'order', 'mark', 'matthew', 'luke', 'not', 'consid', 'respect', 'age', 'say', 'matthew', 'read', 'text', 'mark', 'luke', 'matthew', 'probabl', 'mark', 'version', 'usual', 'theori', 'heard', 'matthew', 'lukeindepend', 'reli', 'mark', 'q', 'one', 'would', 't

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer( max_features =5000)
X = vectorizer.fit_transform(corpus)

In [ ]:
print(X.toarray())
X=X.toarray()
print(vectorizer.get_feature_names())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
['aa', 'aario', 'aau', 'ab', 'abc', 'abil', 'abl', 'abo', 'abort', 'absenc', 'absolut', 'abstract', 'absurd', 'abus', 'ac', 'academ', 'acc', 'acceler', 'accept', 'access', 'accid', 'accord', 'account', 'accur', 'accus', 'ace', 'achiev', 'acj', 'ack', 'acknowledg', 'acm', 'acn', 'acoop', 'acpub', 'acquir', 'across', 'acsc', 'acsu', 'act', 'action', 'activ', 'actix', 'actual', 'ad', 'adam', 'adapt', 'adaptec', 'add', 'addit', 'address', 'adequ', 'adjust', 'admin', 'administr', 'admit', 'adob', 'adult', 'advanc', 'advantag', 'advers', 'advertis', 'advic', 'advis', 'ae', 'aew', 'af', 'aff', 'affect', 'afford', 'afg', 'afraid', 'ag', 'age', 'agenc', 'agnost', 'agnostic', 'ago', 'agre', 'agreement', 'ah', 'ahead', 'ahf', 'ahfm', 'ahl', 'ai', 'aid', 'aim', 'aip', 'air', 'airm', 'aix', 'aiyar', 'aj', 'ajm', 'ajr', 'ajw', 'ajz', 'ak', 'aka', 'al', 'ala', 'alabama', 'alan', 'al

#Test and Train Data split

In [ ]:
# Generating test and train data set 

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)


#GaussianNB model

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()

classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("accuracy of model :" ,accuracy_score(y_test, y_pred))

[[102   1   0   0]
 [  0  94   8  12]
 [  0   7  84  24]
 [  1   9  12  95]]
accuracy of model : 0.8351893095768375


#Logistic Regression model

In [ ]:
from sklearn import linear_model
#(X, y) = (features matrix, labels)
maxent = linear_model.LogisticRegression(penalty='l2', C=0.1)
maxent.fit(X_train, y_train)

y_predicted = maxent.predict(X_test)

print("accuracy of model :" ,np.around(accuracy_score(y_test, y_predicted)*100))

accuracy of model : 93.0


# Own implementation


In [ ]:
print(len(X_train))
print(y_train)
print(len(y_train))
print(len(vectorizer.get_feature_names()))

1796
[1, 1, 1, 2, 3, 1, 2, 2, 1, 1, 0, 3, 2, 1, 0, 0, 1, 2, 3, 1, 3, 3, 3, 1, 2, 0, 0, 2, 0, 0, 3, 0, 2, 2, 1, 0, 1, 1, 3, 1, 0, 1, 1, 2, 0, 1, 1, 2, 1, 1, 3, 1, 1, 1, 1, 2, 3, 2, 0, 2, 2, 1, 0, 0, 0, 3, 1, 3, 1, 1, 2, 0, 1, 1, 2, 2, 1, 0, 2, 0, 3, 3, 1, 3, 3, 2, 2, 1, 3, 2, 2, 2, 3, 3, 2, 2, 0, 2, 0, 2, 0, 3, 3, 3, 1, 1, 2, 1, 1, 2, 3, 2, 0, 2, 3, 1, 0, 3, 1, 1, 0, 1, 3, 1, 2, 3, 3, 3, 0, 2, 3, 1, 2, 2, 2, 2, 0, 2, 0, 3, 3, 3, 3, 2, 2, 3, 3, 3, 2, 0, 0, 1, 3, 2, 0, 3, 1, 0, 3, 3, 1, 1, 1, 0, 3, 1, 1, 2, 1, 2, 1, 0, 1, 0, 1, 2, 3, 3, 0, 2, 1, 1, 0, 1, 0, 0, 3, 1, 3, 1, 2, 2, 1, 1, 2, 2, 0, 2, 2, 0, 1, 3, 2, 3, 0, 3, 1, 3, 0, 0, 1, 2, 0, 3, 2, 2, 1, 3, 0, 2, 1, 3, 0, 3, 3, 3, 2, 0, 1, 3, 1, 3, 3, 3, 3, 1, 0, 3, 0, 1, 2, 1, 3, 2, 1, 1, 3, 0, 0, 3, 3, 0, 1, 3, 2, 0, 2, 0, 1, 2, 1, 0, 1, 3, 1, 1, 0, 3, 2, 3, 1, 3, 2, 3, 2, 3, 1, 0, 1, 3, 3, 2, 0, 1, 1, 2, 3, 2, 1, 1, 0, 3, 0, 0, 0, 0, 2, 0, 2, 1, 0, 2, 1, 1, 1, 3, 2, 0, 3, 1, 1, 2, 3, 3, 1, 2, 2, 0, 3, 2, 0, 2, 0, 1, 1, 1, 3, 1, 2, 2, 0, 3

In [ ]:
# Initializing varaibles
# Finding count of rows corresponding to each class in train set

classes = len(all_subdirs)
total_features = len(vectorizer.get_feature_names())
totoal_rows = len(y_train)
p_c=[]

print(total_features)
values, counts = np.unique(y_train, return_counts=True)
print(values)
print(counts)


5000
[0 1 2 3]
[377 470 476 473]


In [ ]:
# Calculating word counts in each class and total word counts in each class

pre = 0
total_word_class_counts = [[0 for j in range(total_features)] for i in range(classes)]
# print(len(total_word_class_counts[0]))
total_class_counts = [0 for j in range(classes)]


for i in range(totoal_rows):
     
     index = y_train[i]
     print(index , end=" ")
     class_count =0
     for j in range(total_features):

       class_count+=X_train[i][j]

       total_word_class_counts[index][j]+=X_train[i][j]
     total_class_counts[index]+=class_count
    



# for i in counts:
#   total_word_class_counts.append(df.iloc[ pre : i].sum())
#   pre=i

1 1 1 2 3 1 2 2 1 1 0 3 2 1 0 0 1 2 3 1 3 3 3 1 2 0 0 2 0 0 3 0 2 2 1 0 1 1 3 1 0 1 1 2 0 1 1 2 1 1 3 1 1 1 1 2 3 2 0 2 2 1 0 0 0 3 1 3 1 1 2 0 1 1 2 2 1 0 2 0 3 3 1 3 3 2 2 1 3 2 2 2 3 3 2 2 0 2 0 2 0 3 3 3 1 1 2 1 1 2 3 2 0 2 3 1 0 3 1 1 0 1 3 1 2 3 3 3 0 2 3 1 2 2 2 2 0 2 0 3 3 3 3 2 2 3 3 3 2 0 0 1 3 2 0 3 1 0 3 3 1 1 1 0 3 1 1 2 1 2 1 0 1 0 1 2 3 3 0 2 1 1 0 1 0 0 3 1 3 1 2 2 1 1 2 2 0 2 2 0 1 3 2 3 0 3 1 3 0 0 1 2 0 3 2 2 1 3 0 2 1 3 0 3 3 3 2 0 1 3 1 3 3 3 3 1 0 3 0 1 2 1 3 2 1 1 3 0 0 3 3 0 1 3 2 0 2 0 1 2 1 0 1 3 1 1 0 3 2 3 1 3 2 3 2 3 1 0 1 3 3 2 0 1 1 2 3 2 1 1 0 3 0 0 0 0 2 0 2 1 0 2 1 1 1 3 2 0 3 1 1 2 3 3 1 2 2 0 3 2 0 2 0 1 1 1 3 1 2 2 0 3 1 1 3 0 1 1 3 2 3 2 2 1 2 1 1 2 1 3 3 3 3 0 0 2 3 3 3 0 0 3 3 1 3 2 3 1 0 3 1 2 2 0 1 0 2 3 0 0 2 2 0 2 3 0 1 0 2 3 3 2 0 1 3 2 3 0 2 1 3 1 1 3 3 2 2 2 3 2 0 3 3 2 1 0 2 3 0 3 0 2 1 0 2 2 1 1 2 3 0 1 0 2 0 3 3 2 2 0 2 0 0 2 2 1 3 2 1 2 3 1 1 3 1 1 3 3 2 3 0 0 1 3 3 1 2 2 3 0 0 3 3 0 3 0 1 1 1 1 1 0 1 0 1 3 3 0 3 2 1 1 1 2 3 0 1 0 1 1 

In [ ]:
# Printing word count of each class and total count in each class

for i in total_word_class_counts:

   print(i)
   sum =0
   for j in i:
     sum+=j
   print(sum)
print(total_class_counts)

[0, 8, 0, 0, 2, 18, 41, 9, 14, 4, 31, 4, 13, 6, 52, 2, 0, 0, 96, 12, 9, 37, 20, 12, 14, 0, 5, 0, 1, 3, 4, 1, 9, 0, 2, 5, 0, 1, 64, 65, 32, 0, 72, 8, 11, 4, 0, 10, 12, 13, 3, 0, 3, 2, 22, 2, 10, 4, 3, 5, 0, 4, 4, 0, 0, 0, 0, 9, 1, 0, 4, 0, 13, 9, 13, 11, 17, 77, 5, 7, 3, 0, 0, 0, 0, 8, 1, 0, 4, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 15, 0, 0, 0, 0, 0, 0, 1, 0, 6, 0, 21, 0, 0, 0, 3, 0, 17, 4, 34, 69, 4, 4, 10, 0, 60, 39, 18, 29, 2, 0, 21, 140, 71, 4, 38, 24, 37, 0, 6, 0, 0, 2, 15, 41, 1, 0, 0, 25, 7, 13, 12, 0, 15, 7, 0, 23, 0, 5, 1, 0, 35, 1, 16, 18, 2, 56, 16, 3, 1, 1, 74, 0, 76, 24, 0, 10, 3, 77, 71, 30, 10, 0, 0, 14, 0, 15, 0, 2, 11, 0, 22, 11, 23, 50, 45, 13, 4, 17, 8, 11, 8, 154, 5, 0, 1, 10, 10, 10, 0, 5, 0, 0, 0, 11, 14, 0, 49, 11, 136, 0, 1, 7, 1, 15, 0, 2, 54, 0, 7, 9, 16, 0, 0, 337, 8, 1, 0, 1, 13, 0, 0, 3, 71, 0, 10, 0, 11, 4, 29, 12, 4, 13, 8, 75, 34, 2, 0, 0, 5, 1, 0, 0, 221, 9, 371, 0, 1, 0, 3, 0, 0, 14, 4, 4, 23, 39, 2, 10, 11, 87, 0, 0, 1, 0, 0, 22, 0, 14, 4, 4, 56, 0, 0, 0, 3, 0

In [ ]:
# Returns probability of a  row belonging to a class

def prob ( row , curr_class) :
  
  q = (np.log(counts[curr_class]  ) - np.log(totoal_rows))

  for i in range(total_features) :
    if row[i] != 0:
      pos = i
      counts_in_class = total_word_class_counts[curr_class][pos] + 1
      total_count = total_class_counts[curr_class]+total_features+1

      # p*=( counts_in_class/total_count)
      q+= (row[i]*(np.log(counts_in_class)- np.log(total_count) ))

  # p*=(counts[curr_class]/totoal_rows)


  # print("curr class :"  ,curr_class , " "  , q ,end=" ")
  return q


In [ ]:
# Predicting class of a row ( a row in a test data set )

def predict( row) :
  p= -2000000
  curr_class = -1
  for i in range(classes):
    l = prob( row , i)
    if l >= p :
      p = l
      curr_class = i
      # print(curr_class , " " , p )
  # print(curr_class ,end=" ")
  return curr_class

In [ ]:
# Predicting values for test data

y_ans = []
# predict(X_test[1])
for i in X_test:
  # for j in i:
  #   print(j ,end =" ")
  # print()
  k =predict(i)
  y_ans.append(k)


In [ ]:
# Printing predicted and original classes for corresponding rows in test data

print(y_ans)
print(y_test)


[3, 0, 1, 3, 0, 0, 3, 3, 3, 0, 3, 3, 0, 0, 3, 1, 3, 1, 3, 1, 1, 0, 3, 0, 0, 0, 3, 3, 1, 0, 0, 3, 1, 0, 1, 3, 3, 3, 1, 0, 1, 1, 1, 3, 1, 3, 0, 2, 1, 0, 1, 1, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 3, 0, 0, 1, 0, 0, 1, 3, 3, 2, 3, 1, 1, 0, 3, 3, 1, 3, 1, 3, 3, 3, 1, 1, 1, 1, 3, 3, 3, 1, 3, 1, 0, 3, 3, 0, 1, 3, 3, 0, 2, 1, 3, 0, 0, 1, 3, 3, 1, 0, 1, 1, 3, 0, 1, 0, 1, 1, 1, 1, 0, 3, 3, 3, 3, 3, 3, 1, 0, 3, 0, 3, 3, 1, 3, 3, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 3, 3, 0, 3, 0, 3, 1, 1, 1, 1, 0, 1, 1, 1, 3, 3, 3, 1, 3, 1, 3, 3, 0, 3, 3, 1, 3, 1, 3, 3, 1, 1, 1, 0, 0, 1, 1, 3, 0, 3, 1, 3, 1, 3, 3, 3, 3, 0, 3, 1, 3, 3, 3, 1, 1, 1, 0, 1, 3, 3, 1, 0, 1, 1, 1, 0, 3, 1, 0, 3, 1, 1, 1, 1, 3, 3, 0, 1, 3, 3, 3, 2, 1, 0, 0, 1, 3, 3, 0, 3, 3, 1, 0, 3, 0, 1, 3, 1, 0, 0, 0, 3, 1, 1, 1, 1, 0, 1, 3, 0, 3, 3, 0, 3, 3, 3, 3, 1, 3, 1, 1, 3, 3, 3, 3, 1, 0, 0, 1, 0, 3, 3, 3, 3, 3, 3, 1, 1, 0, 0, 3, 1, 1, 0, 1, 3, 3, 1, 1, 3, 3, 3, 3, 3, 0, 3, 3, 3, 0, 1, 0, 1, 3, 1, 3, 1, 0, 0, 0, 1, 3, 3, 3, 1, 3, 3, 1, 2, 3, 3, 1, 1, 1, 0, 0, 

In [ ]:
# Metrics calculation

cm = confusion_matrix(y_ans, y_pred)
print(cm)
print("accuracy of model :" ,accuracy_score(y_test, y_ans))

[[101   1   0   0]
 [  1  98  34  18]
 [  0   0   8   0]
 [  1  12  62 113]]
accuracy of model : 0.7305122494432071
